[package]
name = "playing-with-hlists"
version = "0.1.0"
edition = "2021"
description = "Heterogeneous list usage examples"
license = "MIT/Apache-2.0"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
